In [1]:
#1. Check missing values in the *Age* column (211 missing records).
import pandas as pd
df=pd.read_csv("/content/Employee_dataset.csv")
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [2]:
df["Age"].isnull().sum()

np.int64(211)

In [3]:
df.dtypes

Employee_ID           object
First_Name            object
Last_Name             object
Age                  float64
Department_Region     object
Status                object
Join_Date             object
Salary               float64
Email                 object
Phone                  int64
Performance_Score     object
Remote_Work             bool
dtype: object

In [4]:
#2. Fill missing values in *Age* using mean, median, or mode.

df["Age"].fillna(df["Age"].mean(),inplace=True)

/tmp/ipykernel_2539/1644572501.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

In [5]:
df.isnull().sum()

Employee_ID           0
First_Name            0
Last_Name             0
Age                   0
Department_Region     0
Status                0
Join_Date             0
Salary               24
Email                 0
Phone                 0
Performance_Score     0
Remote_Work           0
dtype: int64

In [6]:
#3. Check missing values in the *Salary* column (24 missing records).
df["Salary"].isnull().sum()

np.int64(24)

In [7]:
#4. Fill missing values in *Salary* using mean or median.
df["Salary"].fillna(df["Salary"].mean(),inplace=True)

/tmp/ipykernel_2539/793365326.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].mean(),inplace=True)

In [8]:
df.isnull().sum()

Employee_ID          0
First_Name           0
Last_Name            0
Age                  0
Department_Region    0
Status               0
Join_Date            0
Salary               0
Email                0
Phone                0
Performance_Score    0
Remote_Work          0
dtype: int64

In [9]:
#5. Convert *Join_Date* from object/string to datetime format.
df["Join_Date"]=pd.to_datetime(df["Join_Date"],errors="coerce")
df.head()
df["Join_Date"].dtype

dtype('<M8[ns]')

In [10]:
#6. Verify *Age* is stored as integer after cleaning.
df["Age"].dtypes

dtype('float64')

In [11]:
#7. Verify *Salary* is stored as float.
df["Salary"].dtypes

dtype('float64')

In [12]:
#8. Convert *Remote_Work* to proper boolean format if needed.
df["Remote_Work"].dtypes

dtype('bool')

In [14]:
#9. Check phone numbers having fewer than 10 digits.
(df["Phone"].astype(str).str.len()<10).sum()

np.int64(92)

In [15]:
#10. Check phone numbers having more than 10 digits.
(df["Phone"].astype(str).str.len()>10).sum()

np.int64(0)

In [13]:
#11. Remove negative signs from phone numbers.
df["Phone"]=df["Phone"].abs()

In [16]:
df["Phone"]

0       1651623197
1       1898471390
2       5596363211
3       3476490784
4       1586734256
           ...
1015    3546212759
1016    2508261122
1017    1261632487
1018    8995729892
1019    7629745492
Name: Phone, Length: 1020, dtype: int64

In [17]:
#12. Standardize phone numbers to a fixed 10-digit format.
df["Phone"].head()
(df["Phone"].astype(str).str.len()==10).sum()# Check all are 10 digits

np.int64(928)

In [18]:
df["Phone"].astype(str).str.len().value_counts()

Phone
10    928
9      78
8      12
7       2
Name: count, dtype: int64

In [19]:
#13. Convert phone numbers to string datatype.
df["Phone"]=df["Phone"].astype(str)
df["Phone"].dtype
print(df["Phone"])

0       1651623197
1       1898471390
2       5596363211
3       3476490784
4       1586734256
           ...
1015    3546212759
1016    2508261122
1017    1261632487
1018    8995729892
1019    7629745492
Name: Phone, Length: 1020, dtype: object

In [20]:
#14. Check duplicate email addresses.
df.duplicated(subset=["Email"]).sum()

np.int64(956)

In [21]:
#15. Verify email format contains '@'.
df[df["Email"].str.contains("@")]

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.000000,DevOps-California,Active,2021-04-02,59767.650000,bob.davis@example.com,1651623197,Average,True
1,EMP1001,Bob,Brown,32.484549,Finance-Texas,Active,2020-07-10,65304.660000,bob.brown@example.com,1898471390,Excellent,True
2,EMP1002,Alice,Jones,32.484549,Admin-Nevada,Pending,2023-12-07,88145.900000,alice.jones@example.com,5596363211,Good,True
3,EMP1003,Eva,Davis,25.000000,Admin-Nevada,Inactive,2021-11-27,69450.990000,eva.davis@example.com,3476490784,Good,True
4,EMP1004,Frank,Williams,25.000000,Cloud Tech-Florida,Active,2022-01-05,109324.610000,frank.williams@example.com,1586734256,Poor,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30.000000,HR-California,Active,2023-08-19,85155.056396,david.miller@example.com,3546212759,Good,True
1016,EMP2016,David,Johnson,30.000000,Cloud Tech-Texas,Inactive,2021-11-07,100215.060000,david.johnson@example.com,2508261122,Good,True
1017,EMP2017,Charlie,Williams,40.000000,Finance-New York,Active,2023-10-04,114587.110000,charlie.williams@example.com,1261632487,Average,False
1018,EMP2018,Alice,Garcia,30.000000,HR-Florida,Inactive,2024-12-16,71318.790000,alice.garcia@example.com,8995729892,Good,True
1019,EMP2019,Heidi,Jones,30.000000,DevOps-Illinois,Pending,2021-02-22,77764.240000,heidi.jones@example.com,7629745492,Average,False

In [22]:
#16. Verify email format contains '.com'.
df[df["Email"].str.contains(".com")]

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.000000,DevOps-California,Active,2021-04-02,59767.650000,bob.davis@example.com,1651623197,Average,True
1,EMP1001,Bob,Brown,32.484549,Finance-Texas,Active,2020-07-10,65304.660000,bob.brown@example.com,1898471390,Excellent,True
2,EMP1002,Alice,Jones,32.484549,Admin-Nevada,Pending,2023-12-07,88145.900000,alice.jones@example.com,5596363211,Good,True
3,EMP1003,Eva,Davis,25.000000,Admin-Nevada,Inactive,2021-11-27,69450.990000,eva.davis@example.com,3476490784,Good,True
4,EMP1004,Frank,Williams,25.000000,Cloud Tech-Florida,Active,2022-01-05,109324.610000,frank.williams@example.com,1586734256,Poor,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30.000000,HR-California,Active,2023-08-19,85155.056396,david.miller@example.com,3546212759,Good,True
1016,EMP2016,David,Johnson,30.000000,Cloud Tech-Texas,Inactive,2021-11-07,100215.060000,david.johnson@example.com,2508261122,Good,True
1017,EMP2017,Charlie,Williams,40.000000,Finance-New York,Active,2023-10-04,114587.110000,charlie.williams@example.com,1261632487,Average,False
1018,EMP2018,Alice,Garcia,30.000000,HR-Florida,Inactive,2024-12-16,71318.790000,alice.garcia@example.com,8995729892,Good,True
1019,EMP2019,Heidi,Jones,30.000000,DevOps-Illinois,Pending,2021-02-22,77764.240000,heidi.jones@example.com,7629745492,Average,False

In [23]:
#17. Remove leading and trailing spaces from email addresses.
df["Email"]=df["Email"].astype(str).str.strip()
print(df["Email"])

0              bob.davis@example.com
1              bob.brown@example.com
2            alice.jones@example.com
3              eva.davis@example.com
4         frank.williams@example.com
                    ...
1015        david.miller@example.com
1016       david.johnson@example.com
1017    charlie.williams@example.com
1018        alice.garcia@example.com
1019         heidi.jones@example.com
Name: Email, Length: 1020, dtype: object

In [24]:
#18. Convert emails to lowercase.
df["Email"]=df["Email"].astype(str).str.lower()
print(df["Email"])

0              bob.davis@example.com
1              bob.brown@example.com
2            alice.jones@example.com
3              eva.davis@example.com
4         frank.williams@example.com
                    ...
1015        david.miller@example.com
1016       david.johnson@example.com
1017    charlie.williams@example.com
1018        alice.garcia@example.com
1019         heidi.jones@example.com
Name: Email, Length: 1020, dtype: object

In [25]:
#19. Remove leading spaces from *First_Name*.
#20. Remove trailing spaces from *First_Name*.
df["First_Name"]=df["First_Name"].astype(str).str.strip()
print(df["First_Name"])

0           Bob
1           Bob
2         Alice
3           Eva
4         Frank
         ...
1015      David
1016      David
1017    Charlie
1018      Alice
1019      Heidi
Name: First_Name, Length: 1020, dtype: object

In [26]:
#21. Remove leading spaces from *Last_Name*.
#22. Remove trailing spaces from *Last_Name*.
df["Last_Name"]=df["Last_Name"].astype(str).str.strip()
print(df["Last_Name"])

0          Davis
1          Brown
2          Jones
3          Davis
4       Williams
          ...
1015      Miller
1016     Johnson
1017    Williams
1018      Garcia
1019       Jones
Name: Last_Name, Length: 1020, dtype: object

In [27]:
#23. Remove extra spaces from *Department_Region*.
df["Department_Region"]=df["Department_Region"].astype(str).str.strip()
print(df["Department_Region"])

0        DevOps-California
1            Finance-Texas
2             Admin-Nevada
3             Admin-Nevada
4       Cloud Tech-Florida
               ...
1015         HR-California
1016      Cloud Tech-Texas
1017      Finance-New York
1018            HR-Florida
1019       DevOps-Illinois
Name: Department_Region, Length: 1020, dtype: object

In [29]:
#24. Standardize text capitalization in name columns.
df["First_Name"]=df["First_Name"].astype(str).str.title()
print(df["First_Name"])

0           Bob
1           Bob
2         Alice
3           Eva
4         Frank
         ...
1015      David
1016      David
1017    Charlie
1018      Alice
1019      Heidi
Name: First_Name, Length: 1020, dtype: object

In [39]:
#25. Split *Department_Region* into two separate columns:

   # * Department
   # * Region
split_col = df['Department_Region'].astype(str).str.split('-',n=1, expand=True)
df[['Department', 'Region']]=split_col
df[['Department', 'Region']].head()

   Department      Region
0      DevOps  California
1     Finance       Texas
2       Admin      Nevada
3       Admin      Nevada
4  Cloud Tech     Florida

In [41]:
#26. Check for invalid department names.
df["First_Name"].astype(str).str.len().value_counts()

First_Name
5    626
3    269
7    125
Name: count, dtype: int64

           Department  Region
0   DevOps-California     NaN
1       Finance-Texas     NaN
2        Admin-Nevada     NaN
3        Admin-Nevada     NaN
4  Cloud Tech-Florida     NaN