In [1]:
#inner join
import pandas as pd
df1=pd.DataFrame({"ID":[1,2,3,4,5],"Name":["A","B","C","D","E"]})
df2=pd.DataFrame({"ID":[2,4,5,6,7],"City":["Ap","kerala","chennai","mumbai","delhi"]})
result=pd.merge(df1,df2,on="ID",how="inner")
print(result)

   ID Name     City
0   2    B       Ap
1   4    D   kerala
2   5    E  chennai

In [2]:
#left outer join
result=pd.merge(df1,df2,on="ID",how="left")
print(result)

   ID Name     City
0   1    A      NaN
1   2    B       Ap
2   3    C      NaN
3   4    D   kerala
4   5    E  chennai

In [3]:
#right outer join
result=pd.merge(df1,df2,on="ID",how="right")
print(result)

   ID Name     City
0   2    B       Ap
1   4    D   kerala
2   5    E  chennai
3   6  NaN   mumbai
4   7  NaN    delhi

In [4]:
#cross join
result=df1.merge(df2,how="cross")
print(result)

    ID_x Name  ID_y     City
0      1    A     2       Ap
1      1    A     4   kerala
2      1    A     5  chennai
3      1    A     6   mumbai
4      1    A     7    delhi
5      2    B     2       Ap
6      2    B     4   kerala
7      2    B     5  chennai
8      2    B     6   mumbai
9      2    B     7    delhi
10     3    C     2       Ap
11     3    C     4   kerala
12     3    C     5  chennai
13     3    C     6   mumbai
14     3    C     7    delhi
15     4    D     2       Ap
16     4    D     4   kerala
17     4    D     5  chennai
18     4    D     6   mumbai
19     4    D     7    delhi
20     5    E     2       Ap
21     5    E     4   kerala
22     5    E     5  chennai
23     5    E     6   mumbai
24     5    E     7    delhi

In [7]:
#self join
df1=pd.DataFrame({"ID":[1,2,3,4,5],"Name":["A","B","C","D","E"],"Salary":[100,120,200,400,500]})
result=df1.merge(df1,left_on="Salary",right_on="ID",how="inner",suffixes=('(e)','(m)'))
print(result)

Empty DataFrame
Columns: [ID(e), Name(e), Salary(e), ID(m), Name(m), Salary(m)]
Index: []

In [8]:
df=pd.read_csv("/content/Customers.csv")
df.head()

   CustomerID  CustomerName       City
0         101   Amit Sharma      Delhi
1         102   Priya Singh     Mumbai
2         103   Rahul Verma       Pune
3         104    Neha Gupta     Jaipur
4         105  Vikram Patel  Ahmedabad

In [9]:
pro=pd.read_csv("/content/Orders.csv")
pro.head()

   OrderID  CustomerID     Product  Amount
0     1001         101      Laptop   55000
1     1002         102      Mobile   25000
2     1003         103  Headphones    3000
3     1004         101       Mouse     800
4     1005         105    Keyboard    1500

In [12]:
#1. Display all customer details along with their orders using an Inner Join.
result=pd.merge(df,pro,on="CustomerID",how="inner")
print(result)

   CustomerID  CustomerName       City  OrderID     Product  Amount
0         101   Amit Sharma      Delhi     1001      Laptop   55000
1         101   Amit Sharma      Delhi     1004       Mouse     800
2         102   Priya Singh     Mumbai     1002      Mobile   25000
3         103   Rahul Verma       Pune     1003  Headphones    3000
4         103   Rahul Verma       Pune     1010     Speaker    2500
5         105  Vikram Patel  Ahmedabad     1005    Keyboard    1500
6         107   Rohan Mehta      Surat     1006     Monitor   12000
7         108   Kiran Yadav    Lucknow     1007     Printer    7000

In [32]:
#2. Show only those customers who have placed at least one order.
result=pd.merge(df,pro,on="CustomerID",how="inner")
print(result)

   CustomerID  CustomerName       City  OrderID     Product  Amount
0         101   Amit Sharma      Delhi     1001      Laptop   55000
1         101   Amit Sharma      Delhi     1004       Mouse     800
2         102   Priya Singh     Mumbai     1002      Mobile   25000
3         103   Rahul Verma       Pune     1003  Headphones    3000
4         103   Rahul Verma       Pune     1010     Speaker    2500
5         105  Vikram Patel  Ahmedabad     1005    Keyboard    1500
6         107   Rohan Mehta      Surat     1006     Monitor   12000
7         108   Kiran Yadav    Lucknow     1007     Printer    7000

In [14]:
#3. Display all customers even if they have not placed any orders (Left Join).
result=pd.merge(df,pro,on="CustomerID",how="left")
print(result)

    CustomerID  CustomerName       City  OrderID     Product   Amount
0          101   Amit Sharma      Delhi   1001.0      Laptop  55000.0
1          101   Amit Sharma      Delhi   1004.0       Mouse    800.0
2          102   Priya Singh     Mumbai   1002.0      Mobile  25000.0
3          103   Rahul Verma       Pune   1003.0  Headphones   3000.0
4          103   Rahul Verma       Pune   1010.0     Speaker   2500.0
5          104    Neha Gupta     Jaipur      NaN         NaN      NaN
6          105  Vikram Patel  Ahmedabad   1005.0    Keyboard   1500.0
7          106   Sneha Joshi     Indore      NaN         NaN      NaN
8          107   Rohan Mehta      Surat   1006.0     Monitor  12000.0
9          108   Kiran Yadav    Lucknow   1007.0     Printer   7000.0
10         109    Anjali Roy    Kolkata      NaN         NaN      NaN
11         110   Arjun Kumar    Chennai      NaN         NaN      NaN

In [17]:
#4. Find customers who have never placed an order.
customers_no_orders = df[df['CustomerID'].isna()][['CustomerID', 'CustomerName', 'City']]
print(customers_no_orders)

Empty DataFrame
Columns: [CustomerID, CustomerName, City]
Index: []

In [18]:
#5. Display all orders even if customer information is missing (Right Join).
result=pd.merge(df,pro,on="CustomerID",how="right")
print(result)

   CustomerID  CustomerName       City  OrderID     Product  Amount
0         101   Amit Sharma      Delhi     1001      Laptop   55000
1         102   Priya Singh     Mumbai     1002      Mobile   25000
2         103   Rahul Verma       Pune     1003  Headphones    3000
3         101   Amit Sharma      Delhi     1004       Mouse     800
4         105  Vikram Patel  Ahmedabad     1005    Keyboard    1500
5         107   Rohan Mehta      Surat     1006     Monitor   12000
6         108   Kiran Yadav    Lucknow     1007     Printer    7000
7         111           NaN        NaN     1008      Tablet   18000
8         112           NaN        NaN     1009      Camera   30000
9         103   Rahul Verma       Pune     1010     Speaker    2500

In [33]:
#6. Find orders whose CustomerID does not exist in the Customers table.
result=pd.merge(df,pro,on="CustomerID",how="outer")
print(result)

    CustomerID  CustomerName       City  OrderID     Product   Amount
0          101   Amit Sharma      Delhi   1001.0      Laptop  55000.0
1          101   Amit Sharma      Delhi   1004.0       Mouse    800.0
2          102   Priya Singh     Mumbai   1002.0      Mobile  25000.0
3          103   Rahul Verma       Pune   1003.0  Headphones   3000.0
4          103   Rahul Verma       Pune   1010.0     Speaker   2500.0
5          104    Neha Gupta     Jaipur      NaN         NaN      NaN
6          105  Vikram Patel  Ahmedabad   1005.0    Keyboard   1500.0
7          106   Sneha Joshi     Indore      NaN         NaN      NaN
8          107   Rohan Mehta      Surat   1006.0     Monitor  12000.0
9          108   Kiran Yadav    Lucknow   1007.0     Printer   7000.0
10         109    Anjali Roy    Kolkata      NaN         NaN      NaN
11         110   Arjun Kumar    Chennai      NaN         NaN      NaN
12         111           NaN        NaN   1008.0      Tablet  18000.0
13         112           NaN        NaN   1009.0      Camera  30000.0

In [34]:
#7. Perform a Full Outer Join between Customers and Orders.
result=pd.merge(df,pro,on="CustomerID",how="outer")
print(result)

    CustomerID  CustomerName       City  OrderID     Product   Amount
0          101   Amit Sharma      Delhi   1001.0      Laptop  55000.0
1          101   Amit Sharma      Delhi   1004.0       Mouse    800.0
2          102   Priya Singh     Mumbai   1002.0      Mobile  25000.0
3          103   Rahul Verma       Pune   1003.0  Headphones   3000.0
4          103   Rahul Verma       Pune   1010.0     Speaker   2500.0
5          104    Neha Gupta     Jaipur      NaN         NaN      NaN
6          105  Vikram Patel  Ahmedabad   1005.0    Keyboard   1500.0
7          106   Sneha Joshi     Indore      NaN         NaN      NaN
8          107   Rohan Mehta      Surat   1006.0     Monitor  12000.0
9          108   Kiran Yadav    Lucknow   1007.0     Printer   7000.0
10         109    Anjali Roy    Kolkata      NaN         NaN      NaN
11         110   Arjun Kumar    Chennai      NaN         NaN      NaN
12         111           NaN        NaN   1008.0      Tablet  18000.0
13         112           NaN        NaN   1009.0      Camera  30000.0

In [35]:
#8. Identify records that exist only in Customers but not in Orders.
result=pd.merge(df,pro,on="CustomerID",how="left")
print(result)

    CustomerID  CustomerName       City  OrderID     Product   Amount
0          101   Amit Sharma      Delhi   1001.0      Laptop  55000.0
1          101   Amit Sharma      Delhi   1004.0       Mouse    800.0
2          102   Priya Singh     Mumbai   1002.0      Mobile  25000.0
3          103   Rahul Verma       Pune   1003.0  Headphones   3000.0
4          103   Rahul Verma       Pune   1010.0     Speaker   2500.0
5          104    Neha Gupta     Jaipur      NaN         NaN      NaN
6          105  Vikram Patel  Ahmedabad   1005.0    Keyboard   1500.0
7          106   Sneha Joshi     Indore      NaN         NaN      NaN
8          107   Rohan Mehta      Surat   1006.0     Monitor  12000.0
9          108   Kiran Yadav    Lucknow   1007.0     Printer   7000.0
10         109    Anjali Roy    Kolkata      NaN         NaN      NaN
11         110   Arjun Kumar    Chennai      NaN         NaN      NaN

In [36]:
#9. Identify records that exist only in Orders but not in Customers.
result=pd.merge(df,pro,on="CustomerID",how="right")
print(result)

   CustomerID  CustomerName       City  OrderID     Product  Amount
0         101   Amit Sharma      Delhi     1001      Laptop   55000
1         102   Priya Singh     Mumbai     1002      Mobile   25000
2         103   Rahul Verma       Pune     1003  Headphones    3000
3         101   Amit Sharma      Delhi     1004       Mouse     800
4         105  Vikram Patel  Ahmedabad     1005    Keyboard    1500
5         107   Rohan Mehta      Surat     1006     Monitor   12000
6         108   Kiran Yadav    Lucknow     1007     Printer    7000
7         111           NaN        NaN     1008      Tablet   18000
8         112           NaN        NaN     1009      Camera   30000
9         103   Rahul Verma       Pune     1010     Speaker    2500

In [45]:
#10. Merge Orders and Payments using OrderID.
pay=pd.read_csv("/content/Payments.csv")
pay.head()
result=pd.merge(pro,pay)
print(result)

   OrderID  CustomerID     Product  Amount PaymentID  PaymentMode
0     1001         101      Laptop   55000      P001          UPI
1     1002         102      Mobile   25000      P002  Credit Card
2     1003         103  Headphones    3000      P003         Cash
3     1005         105    Keyboard    1500      P004   Debit Card
4     1006         107     Monitor   12000      P005          UPI
5     1008         111      Tablet   18000      P006  Credit Card

In [44]:
#11. Find orders for which payment information is not available.
result=pd.merge(pro,pay,on="OrderID",how="outer")
print(result)

    OrderID  CustomerID     Product   Amount PaymentID  PaymentMode
0      1001       101.0      Laptop  55000.0      P001          UPI
1      1002       102.0      Mobile  25000.0      P002  Credit Card
2      1003       103.0  Headphones   3000.0      P003         Cash
3      1004       101.0       Mouse    800.0       NaN          NaN
4      1005       105.0    Keyboard   1500.0      P004   Debit Card
5      1006       107.0     Monitor  12000.0      P005          UPI
6      1007       108.0     Printer   7000.0       NaN          NaN
7      1008       111.0      Tablet  18000.0      P006  Credit Card
8      1009       112.0      Camera  30000.0       NaN          NaN
9      1010       103.0     Speaker   2500.0       NaN          NaN
10     1011         NaN         NaN      NaN      P007         Cash

In [ ]:
#12. Find payments that do not have a matching order.