In [132]:
import pandas as pd
df=pd.read_csv("/content/sample_data/Dataset-1.csv")
df.head()

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
0,1,Pooja,18.0,M,Pune,25000.0,HR,Mar 10 2024,9.876543e+09,1.0
1,2,Pooja,40.0,Female,Bhopal,-1000.0,NaN,NaN,1.234500e+04,2.0
2,3,Priya,18.0,F,Bhopal,NaN,IT,15/02/2024,NaN,4.0
3,4,Sneha,30.0,Female,Mumbai,-1000.0,Sales,Mar 10 2024,9.876543e+09,5.0
4,5,Pooja,22.0,M,NaN,55000.0,IT,Mar 10 2024,1.234500e+04,1.0

In [ ]:
df.shape

(5000, 10)

In [ ]:
df.columns

Index(['Customer_ID', 'Name', 'Age', 'Gender', 'City', 'Salary', 'Department',
       'Join_Date', 'Phone', 'Performance_Score'],
      dtype='object')

In [ ]:
df.dtypes

Customer_ID            int64
Name                  object
Age                  float64
Gender                object
City                  object
Salary               float64
Department            object
Join_Date             object
Phone                float64
Performance_Score    float64
dtype: object

In [ ]:
df.describe()

       Customer_ID          Age        Salary         Phone  Performance_Score
count  5000.000000  4436.000000   4126.000000  3.735000e+03        4161.000000
mean   2500.500000    39.494364  31994.183228  6.632526e+09           2.996155
std    1443.520003    44.259140  19329.449100  4.682321e+09           1.428247
min       1.000000    -5.000000  -1000.000000  1.234500e+04           1.000000
25%    1250.750000    18.000000  25000.000000  1.234500e+04           2.000000
50%    2500.500000    25.000000  35000.000000  9.876543e+09           3.000000
75%    3750.250000    35.000000  45000.000000  1.000000e+10           4.000000
max    5000.000000   150.000000  55000.000000  1.000000e+10           5.000000

In [ ]:
df.describe(include="object")

         Name Gender    City Department   Join_Date
count    5000   3969    4280       3967        3705
unique      8      4       6          4           3
top     Rahul   Male  Mumbai      Sales  15/02/2024
freq      643   1005     759       1019        1265

In [ ]:
df["Gender"].value_counts()

Gender
Male      1005
M         1002
Female    1000
F          962
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

Customer_ID             0
Name                    0
Age                   564
Gender               1031
City                  720
Salary                874
Department           1033
Join_Date            1295
Phone                1265
Performance_Score     839
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(7621)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [104]:
df["Age"].fillna(df["Age"].mean(),inplace=True)

/tmp/ipykernel_619/2595122914.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

In [105]:
df.isnull().sum()

Customer_ID             0
Name                    0
Age                     0
Gender               1031
City                  720
Salary                874
Department           1033
Join_Date            1295
Phone                1265
Performance_Score     839
dtype: int64

In [106]:
df["Gender"].fillna(df["Gender"].mode()[0],inplace=True)

/tmp/ipykernel_619/1219453514.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gender"].fillna(df["Gender"].mode()[0],inplace=True)

In [107]:
df.isnull().sum()

Customer_ID             0
Name                    0
Age                     0
Gender                  0
City                  720
Salary                874
Department           1033
Join_Date            1295
Phone                1265
Performance_Score     839
dtype: int64

In [108]:
df["City"].fillna(df["City"].mode()[0],inplace=True)

/tmp/ipykernel_619/3555604006.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["City"].fillna(df["City"].mode()[0],inplace=True)

In [109]:
df.isnull().sum()

Customer_ID             0
Name                    0
Age                     0
Gender                  0
City                    0
Salary                874
Department           1033
Join_Date            1295
Phone                1265
Performance_Score     839
dtype: int64

In [110]:
df["Salary"].fillna(df["Salary"].mean(),inplace=True)

/tmp/ipykernel_619/2156103880.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].mean(),inplace=True)

In [111]:
df.isnull().sum()

Customer_ID             0
Name                    0
Age                     0
Gender                  0
City                    0
Salary                  0
Department           1033
Join_Date            1295
Phone                1265
Performance_Score     839
dtype: int64

In [112]:
df["Department"].fillna(df["Department"].mode()[0],inplace=True)

/tmp/ipykernel_619/1337714153.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Department"].fillna(df["Department"].mode()[0],inplace=True)

In [113]:
df.isnull().sum()

Customer_ID             0
Name                    0
Age                     0
Gender                  0
City                    0
Salary                  0
Department              0
Join_Date            1295
Phone                1265
Performance_Score     839
dtype: int64

In [140]:
df["Join_Date"]=df["Join_Date"].fillna(method="ffill")

/tmp/ipykernel_619/3433342795.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Join_Date"]=df["Join_Date"].fillna(method="ffill")

In [141]:
df.isnull().sum()

Customer_ID             0
Name                    0
Age                   564
Gender               1031
City                  720
Salary                874
Department           1033
Join_Date               0
Phone                1265
Performance_Score     839
dtype: int64

In [116]:
df["Phone"].fillna(df["Phone"].mean(),inplace=True)

/tmp/ipykernel_619/850176796.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Phone"].fillna(df["Phone"].mean(),inplace=True)

In [117]:
df.isnull().sum()

Customer_ID            0
Name                   0
Age                    0
Gender                 0
City                   0
Salary                 0
Department             0
Join_Date              0
Phone                  0
Performance_Score    839
dtype: int64

In [118]:
df["Performance_Score"].fillna(df["Performance_Score"].mean(),inplace=True)

/tmp/ipykernel_619/1285432439.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Performance_Score"].fillna(df["Performance_Score"].mean(),inplace=True)

In [119]:
df.isnull().sum()

Customer_ID          0
Name                 0
Age                  0
Gender               0
City                 0
Salary               0
Department           0
Join_Date            0
Phone                0
Performance_Score    0
dtype: int64

In [120]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
#6. Check whether the Customer_ID column contains duplicate IDs.
df.duplicated(subset=["Customer_ID"]).sum()

np.int64(0)

In [ ]:
#Find records where Age is less than 0.
df[df["Age"]<0]

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
13,14,Rahul,-5.0,Male,Bengaluru,55000.000000,IT,Mar 10 2024,9.876543e+09,3.000000
23,24,Anjali,-5.0,F,Bengaluru,-1000.000000,Sales,15/02/2024,6.632526e+09,5.000000
25,26,Sneha,-5.0,Male,Bengaluru,-1000.000000,IT,15/02/2024,9.876543e+09,5.000000
33,34,Sneha,-5.0,Female,Delhi,25000.000000,IT,2024-01-15,9.876543e+09,3.000000
43,44,Rohit,-5.0,Female,Bengaluru,25000.000000,IT,2024-01-15,1.234500e+04,3.000000
...,...,...,...,...,...,...,...,...,...,...
4965,4966,Priya,-5.0,Male,Mumbai,55000.000000,Finance,15/02/2024,1.000000e+10,4.000000
4971,4972,Rahul,-5.0,M,Bhopal,25000.000000,Finance,15/02/2024,1.000000e+10,4.000000
4972,4973,Anjali,-5.0,Male,Mumbai,45000.000000,Sales,15/02/2024,1.000000e+10,1.000000
4976,4977,Vikas,-5.0,Male,Mumbai,31994.183228,HR,2024-01-15,1.234500e+04,3.000000
4980,4981,Rahul,-5.0,M,Delhi,35000.000000,HR,2024-01-15,1.000000e+10,2.996155

In [ ]:
#8. Find records where Age is greater than 100.
df[df["Age"]>100]

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
24,25,Priya,150.0,Male,Pune,25000.000000,Sales,15/02/2024,1.234500e+04,5.0
31,32,Sneha,150.0,Female,Bhopal,35000.000000,IT,Mar 10 2024,6.632526e+09,5.0
39,40,Anjali,150.0,Male,Delhi,31994.183228,Sales,Mar 10 2024,1.000000e+10,2.0
42,43,Anjali,150.0,F,Delhi,-1000.000000,IT,2024-01-15,1.000000e+10,2.0
51,52,Vikas,150.0,Female,Delhi,55000.000000,Sales,2024-01-15,6.632526e+09,1.0
...,...,...,...,...,...,...,...,...,...,...
4970,4971,Priya,150.0,Male,Delhi,55000.000000,Sales,2024-01-15,1.234500e+04,3.0
4973,4974,Amit,150.0,M,Bengaluru,31994.183228,Finance,Mar 10 2024,1.000000e+10,5.0
4992,4993,Anjali,150.0,Male,Pune,45000.000000,Sales,2024-01-15,1.000000e+10,3.0
4996,4997,Priya,150.0,Male,Delhi,-1000.000000,IT,Mar 10 2024,1.234500e+04,4.0
4998,4999,Vikas,150.0,Male,Mumbai,-1000.000000,HR,Mar 10 2024,1.000000e+10,1.0

In [ ]:
#33. Find the maximum salary.
df["Salary"].max()

55000.0

In [ ]:
#34. Find the minimum salary.
df["Salary"].min()

-1000.0

In [ ]:
#10. Find records where Salary is negative.
df[df["Salary"]<0]

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
1,2,Pooja,40.000000,Female,Bhopal,-1000.0,Sales,Mar 10 2024,1.234500e+04,2.0
3,4,Sneha,30.000000,Female,Mumbai,-1000.0,Sales,Mar 10 2024,9.876543e+09,5.0
18,19,Priya,39.494364,Male,Mumbai,-1000.0,Finance,2024-01-15,1.000000e+10,4.0
23,24,Anjali,-5.000000,F,Bengaluru,-1000.0,Sales,15/02/2024,6.632526e+09,5.0
25,26,Sneha,-5.000000,Male,Bengaluru,-1000.0,IT,15/02/2024,9.876543e+09,5.0
...,...,...,...,...,...,...,...,...,...,...
4987,4988,Rahul,35.000000,M,Bengaluru,-1000.0,IT,Mar 10 2024,6.632526e+09,1.0
4991,4992,Rahul,22.000000,Male,Bhopal,-1000.0,IT,2024-01-15,9.876543e+09,5.0
4994,4995,Sneha,40.000000,M,Bhopal,-1000.0,Finance,2024-01-15,6.632526e+09,3.0
4996,4997,Priya,150.000000,Male,Delhi,-1000.0,IT,Mar 10 2024,1.234500e+04,4.0
4998,4999,Vikas,150.000000,Male,Mumbai,-1000.0,HR,Mar 10 2024,1.000000e+10,1.0

In [ ]:
#11. Replace negative salary values.
if df["Salary"].min()<0:
  df["Salary"].fillna(df["Salary"].mean(),inplace=True)

In [ ]:
df["Salary"]

0       25000.000000
1           0.000000
2       31994.183228
3           0.000000
4       55000.000000
            ...
4995    55000.000000
4996        0.000000
4997    35000.000000
4998        0.000000
4999    45000.000000
Name: Salary, Length: 5000, dtype: float64

In [ ]:
df["Salary"] = df["Salary"].mask(df["Salary"] < 0, 0)

In [ ]:
df[df["Salary"]<0]

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, City, Salary, Department, Join_Date, Phone, Performance_Score]
Index: []

In [ ]:
#19. Convert all city names to proper case.
df["City"]=df["City"].str.title()
df.head()

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
0,1,Pooja,18.0,M,Pune,25000.000000,HR,Mar 10 2024,9.876543e+09,1.0
1,2,Pooja,40.0,Female,Bhopal,0.000000,Sales,Mar 10 2024,1.234500e+04,2.0
2,3,Priya,18.0,F,Bhopal,31994.183228,IT,15/02/2024,6.632526e+09,4.0
3,4,Sneha,30.0,Female,Mumbai,0.000000,Sales,Mar 10 2024,9.876543e+09,5.0
4,5,Pooja,22.0,M,Mumbai,55000.000000,IT,Mar 10 2024,1.234500e+04,1.0

In [ ]:
#20. Find rows where City is missing.
df[df["City"].isna()]

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, City, Salary, Department, Join_Date, Phone, Performance_Score]
Index: []

In [ ]:
#21. Check the data type of each column.
df.dtypes

Customer_ID            int64
Name                  object
Age                  float64
Gender                object
City                  object
Salary               float64
Department            object
Join_Date             object
Phone                float64
Performance_Score    float64
dtype: object

In [ ]:
#17. Find all unique values in the City column.
unique_cities = df["City"].unique()
print(unique_cities)

['Pune' 'Bhopal' 'Mumbai' '  Delhi  ' 'Delhi' 'Bengaluru']

In [ ]:
#16. Find rows where Gender is missing.
df[df["Gender"].isna()]

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, City, Salary, Department, Join_Date, Phone, Performance_Score]
Index: []

In [57]:
#22. Convert the Join_Date column into datetime format.
df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")

In [58]:
df.head()

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
0,1,Pooja,18.0,M,Pune,25000.0,HR,2024-03-10,9.876543e+09,1.0
1,2,Pooja,40.0,Female,Bhopal,-1000.0,NaN,NaT,1.234500e+04,2.0
2,3,Priya,18.0,F,Bhopal,NaN,IT,NaT,NaN,4.0
3,4,Sneha,30.0,Female,Mumbai,-1000.0,Sales,2024-03-10,9.876543e+09,5.0
4,5,Pooja,22.0,M,NaN,55000.0,IT,2024-03-10,1.234500e+04,1.0

In [63]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"], format="%d-%m-%Y")

In [64]:
df.head()

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
0,1,Pooja,18.0,M,Pune,25000.0,HR,2024-03-10,9.876543e+09,1.0
1,2,Pooja,40.0,Female,Bhopal,-1000.0,NaN,2024-03-10,1.234500e+04,2.0
2,3,Priya,18.0,F,Bhopal,NaN,IT,2024-03-10,NaN,4.0
3,4,Sneha,30.0,Female,Mumbai,-1000.0,Sales,2024-03-10,9.876543e+09,5.0
4,5,Pooja,22.0,M,NaN,55000.0,IT,2024-03-10,1.234500e+04,1.0

In [66]:
#23. Find rows where date conversion fails.
df[df["Join_Date"].isna()]

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, City, Salary, Department, Join_Date, Phone, Performance_Score]
Index: []

In [68]:
#24. Extract year from the Join_Date column.
df["Join_Year"] = df["Join_Date"].dt.year
df["Join_Year"]

0       2024
1       2024
2       2024
3       2024
4       2024
        ...
4995    2024
4996    2024
4997    2024
4998    2024
4999    2024
Name: Join_Year, Length: 5000, dtype: int32

In [69]:
#25. Extract month from the Join_Date column.

df["Join_month"] = df["Join_Date"].dt.month
df["Join_month"]

0       3
1       3
2       3
3       3
4       3
       ..
4995    3
4996    3
4997    3
4998    3
4999    3
Name: Join_month, Length: 5000, dtype: int32

In [70]:
#25. Extract day from the Join_Date column.
df["Join_dat"] = df["Join_Date"].dt.date
df["Join_dat"]

0       2024-03-10
1       2024-03-10
2       2024-03-10
3       2024-03-10
4       2024-03-10
           ...
4995    2024-03-10
4996    2024-03-10
4997    2024-03-10
4998    2024-03-10
4999    2024-03-10
Name: Join_dat, Length: 5000, dtype: object

In [99]:
#27. Find phone numbers with less than 10 digits.
df[df["Phone"].astype(str).str.len()<10]

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score,Join_Year,Join_month,Join_dat
1,2,Pooja,40.000000,Female,Bhopal,-1000.000000,Sales,2024-03-10,12345.0,2.000000,2024,3,2024-03-10
4,5,Pooja,22.000000,M,Mumbai,55000.000000,IT,2024-03-10,12345.0,1.000000,2024,3,2024-03-10
5,6,Sneha,22.000000,Female,Delhi,25000.000000,HR,2024-03-10,12345.0,1.000000,2024,3,2024-03-10
24,25,Priya,150.000000,Male,Pune,25000.000000,Sales,2024-03-10,12345.0,5.000000,2024,3,2024-03-10
34,35,Rahul,30.000000,Female,Bengaluru,55000.000000,Sales,2024-03-10,12345.0,2.996155,2024,3,2024-03-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4970,4971,Priya,150.000000,Male,Delhi,55000.000000,Sales,2024-03-10,12345.0,3.000000,2024,3,2024-03-10
4975,4976,Rahul,39.494364,Female,Mumbai,45000.000000,Sales,2024-03-10,12345.0,4.000000,2024,3,2024-03-10
4976,4977,Vikas,-5.000000,Male,Mumbai,31994.183228,HR,2024-03-10,12345.0,3.000000,2024,3,2024-03-10
4982,4983,Vikas,25.000000,Male,Bhopal,31994.183228,Sales,2024-03-10,12345.0,4.000000,2024,3,2024-03-10
4996,4997,Priya,150.000000,Male,Delhi,-1000.000000,IT,2024-03-10,12345.0,4.000000,2024,3,2024-03-10

In [121]:
#28. Find phone numbers containing non-numeric values.
df[~df["Phone"].astype (str).str.isnumeric()]

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
0,1,Pooja,18.0,M,Pune,25000.000000,HR,Mar 10 2024,9.876543e+09,1.000000
1,2,Pooja,40.0,Female,Bhopal,-1000.000000,Sales,Mar 10 2024,1.234500e+04,2.000000
2,3,Priya,18.0,F,Bhopal,31994.183228,IT,15/02/2024,6.632526e+09,4.000000
3,4,Sneha,30.0,Female,Mumbai,-1000.000000,Sales,Mar 10 2024,9.876543e+09,5.000000
4,5,Pooja,22.0,M,Mumbai,55000.000000,IT,Mar 10 2024,1.234500e+04,1.000000
...,...,...,...,...,...,...,...,...,...,...
4995,4996,Rahul,18.0,Male,Delhi,55000.000000,Finance,Mar 10 2024,6.632526e+09,2.996155
4996,4997,Priya,150.0,Male,Delhi,-1000.000000,IT,Mar 10 2024,1.234500e+04,4.000000
4997,4998,Rohit,22.0,Female,Delhi,35000.000000,HR,Mar 10 2024,6.632526e+09,5.000000
4998,4999,Vikas,150.0,Male,Mumbai,-1000.000000,HR,Mar 10 2024,1.000000e+10,1.000000
4999,5000,Anjali,30.0,Female,Delhi,45000.000000,Sales,Mar 10 2024,6.632526e+09,3.000000

In [127]:
#30. Count the number of employees in each department.
df["Department"].value_counts(dropna=False)

Department
Sales      2052
Finance     994
IT          986
HR          968
Name: count, dtype: int64

In [147]:
df["City"].value_counts(dropna=False)

City
Mumbai       759
Pune         739
NaN          720
Bengaluru    716
  Delhi      712
Bhopal       685
Delhi        669
Name: count, dtype: int64

In [128]:
#35. Find the average salary.
df["Salary"].mean()

np.float64(31994.183228308284)

In [129]:
#36. Find the median salary.
df["Salary"].median()

31994.183228308288

In [134]:
#38. Detect salary outliers using IQR.

Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)
IQR = Q3 - Q1


lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df["Salary"] < lower_bound) | (df["Salary"] > upper_bound)]
print(outliers)

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, City, Salary, Department, Join_Date, Phone, Performance_Score]
Index: []

In [135]:
#38. Detect age outliers using IQR.
Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)
IQR = Q3 - Q1


lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df["Age"] < lower_bound) | (df["Age"] > upper_bound)]
print(outliers)

      Customer_ID    Name    Age  Gender       City   Salary Department  \
24             25   Priya  150.0    Male       Pune  25000.0      Sales
31             32   Sneha  150.0  Female     Bhopal  35000.0         IT
39             40  Anjali  150.0    Male    Delhi        NaN        NaN
42             43  Anjali  150.0       F      Delhi  -1000.0         IT
51             52   Vikas  150.0  Female      Delhi  55000.0        NaN
...           ...     ...    ...     ...        ...      ...        ...
4970         4971   Priya  150.0     NaN    Delhi    55000.0      Sales
4973         4974    Amit  150.0       M  Bengaluru      NaN    Finance
4992         4993  Anjali  150.0    Male       Pune  45000.0      Sales
4996         4997   Priya  150.0     NaN    Delhi    -1000.0         IT
4998         4999   Vikas  150.0    Male     Mumbai  -1000.0         HR

        Join_Date         Phone  Performance_Score
24            NaN  1.234500e+04                5.0
31    Mar 10 2024           NaN                5.0
39            NaN  1.000000e+10                2.0
42     2024-01-15  1.000000e+10                2.0
51     2024-01-15           NaN                1.0
...           ...           ...                ...
4970   2024-01-15  1.234500e+04                3.0
4973  Mar 10 2024  1.000000e+10                5.0
4992   2024-01-15  1.000000e+10                3.0
4996  Mar 10 2024  1.234500e+04                4.0
4998          NaN  1.000000e+10                1.0

[569 rows x 10 columns]

In [136]:
#44. Filter employees whose salary is greater than 50,000.
df[df["Salary"]>50000]

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
4,5,Pooja,22.0,M,NaN,55000.0,IT,Mar 10 2024,1.234500e+04,1.0
13,14,Rahul,-5.0,Male,Bengaluru,55000.0,IT,Mar 10 2024,9.876543e+09,3.0
15,16,Priya,25.0,F,Mumbai,55000.0,IT,2024-01-15,1.000000e+10,1.0
17,18,Amit,NaN,M,Bengaluru,55000.0,Sales,Mar 10 2024,NaN,NaN
29,30,Anjali,30.0,Female,Mumbai,55000.0,Finance,15/02/2024,1.000000e+10,5.0
...,...,...,...,...,...,...,...,...,...,...
4981,4982,Priya,22.0,F,Bhopal,55000.0,HR,Mar 10 2024,1.000000e+10,5.0
4986,4987,Sneha,30.0,Male,Mumbai,55000.0,NaN,NaN,NaN,2.0
4988,4989,Rohit,25.0,Female,Delhi,55000.0,NaN,NaN,1.000000e+10,3.0
4990,4991,Amit,NaN,Male,Bengaluru,55000.0,HR,15/02/2024,NaN,2.0
4995,4996,Rahul,18.0,NaN,Delhi,55000.0,Finance,Mar 10 2024,NaN,NaN

In [137]:
#45. Filter employees from Delhi.
df[df["City"]=="Delhi"]

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
10,11,Anjali,22.0,Female,Delhi,25000.0,IT,2024-01-15,9.876543e+09,4.0
21,22,Priya,35.0,NaN,Delhi,35000.0,Finance,2024-01-15,1.000000e+10,NaN
33,34,Sneha,-5.0,Female,Delhi,25000.0,IT,2024-01-15,9.876543e+09,3.0
42,43,Anjali,150.0,F,Delhi,-1000.0,IT,2024-01-15,1.000000e+10,2.0
45,46,Anjali,25.0,M,Delhi,NaN,NaN,NaN,1.234500e+04,2.0
...,...,...,...,...,...,...,...,...,...,...
4955,4956,Priya,25.0,NaN,Delhi,45000.0,NaN,NaN,NaN,3.0
4966,4967,Priya,30.0,Female,Delhi,NaN,Finance,2024-01-15,1.000000e+10,3.0
4978,4979,Rahul,40.0,M,Delhi,-1000.0,Sales,15/02/2024,NaN,1.0
4980,4981,Rahul,-5.0,M,Delhi,35000.0,HR,NaN,1.000000e+10,NaN
4995,4996,Rahul,18.0,NaN,Delhi,55000.0,Finance,Mar 10 2024,NaN,NaN

In [142]:
#46. Find employees who joined after 2024.
df[df["Join_Date"]==2024]

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, City, Salary, Department, Join_Date, Phone, Performance_Score]
Index: []

In [146]:
#48. Rename all column names to lowercase.
df.columns.astype(str).str.lower()

Index(['customer_id', 'name', 'age', 'gender', 'city', 'salary', 'department',
       'join_date', 'phone', 'performance_score'],
      dtype='object')

In [149]:
#49. Create a cleaned version of the dataset.
df["Age"].fillna(df["Age"].mean(),inplace=True)
df["Gender"].fillna(df["Gender"].mode()[0],inplace=True)
df["City"].fillna(df["City"].mode()[0],inplace=True)
df["Salary"].fillna(df["Salary"].mean(),inplace=True)
df["Department"].fillna(df["Department"].mode()[0],inplace=True)
df["Join_Date"]=df["Join_Date"].fillna(method="ffill")
df["Phone"].fillna(df["Phone"].mean(),inplace=True)
df["Performance_Score"].fillna(df["Performance_Score"].mean(),inplace=True)
df.isnull().sum()

/tmp/ipykernel_619/489235355.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)
/tmp/ipykernel_619/489235355.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gender"].fillna(df["Gender"].mode()[0],inplace=True)
/tmp/ipykernel_619/489235355.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["City"].fillna(df["City"].mode()[0],inplace=True)
/tmp/ipykernel_619/489235355.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].mean(),inplace=True)
/tmp/ipykernel_619/489235355.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Department"].fillna(df["Department"].mode()[0],inplace=True)
/tmp/ipykernel_619/489235355.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Join_Date"]=df["Join_Date"].fillna(method="ffill")
/tmp/ipykernel_619/489235355.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Phone"].fillna(df["Phone"].mean(),inplace=True)
/tmp/ipykernel_619/489235355.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Performance_Score"].fillna(df["Performance_Score"].mean(),inplace=True)

Customer_ID          0
Name                 0
Age                  0
Gender               0
City                 0
Salary               0
Department           0
Join_Date            0
Phone                0
Performance_Score    0
dtype: int64

In [151]:
df.duplicated().sum()

np.int64(0)

In [153]:
#50. Save the cleaned dataset as cleaned_dataset.csv.
df.to_csv("cleaned_dataset.csv", index=False)

In [154]:
cl=pd.read_csv("cleaned_dataset.csv")

In [155]:
cl.head()

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
0,1,Pooja,18.0,M,Pune,25000.000000,HR,Mar 10 2024,9.876543e+09,1.0
1,2,Pooja,40.0,Female,Bhopal,-1000.000000,Sales,Mar 10 2024,1.234500e+04,2.0
2,3,Priya,18.0,F,Bhopal,31994.183228,IT,15/02/2024,6.632526e+09,4.0
3,4,Sneha,30.0,Female,Mumbai,-1000.000000,Sales,Mar 10 2024,9.876543e+09,5.0
4,5,Pooja,22.0,M,Mumbai,55000.000000,IT,Mar 10 2024,1.234500e+04,1.0

In [158]:
cl.tail()

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
4995,4996,Rahul,18.0,Male,Delhi,55000.0,Finance,Mar 10 2024,6.632526e+09,2.996155
4996,4997,Priya,150.0,Male,Delhi,-1000.0,IT,Mar 10 2024,1.234500e+04,4.000000
4997,4998,Rohit,22.0,Female,Delhi,35000.0,HR,Mar 10 2024,6.632526e+09,5.000000
4998,4999,Vikas,150.0,Male,Mumbai,-1000.0,HR,Mar 10 2024,1.000000e+10,1.000000
4999,5000,Anjali,30.0,Female,Delhi,45000.0,Sales,Mar 10 2024,6.632526e+09,3.000000