In [1]:
import pandas as pd
df=pd.read_csv("/sales_data-1.csv")
df.head()

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Sales
0,1001,2025-01-01,Simran,Delhi,Sofa,Furniture,9,32551,5,278311.05
1,1002,2025-01-02,Mohit,Mumbai,Laptop,Electronics,2,49140,20,78624.00
2,1003,2025-01-03,Arjun,Hyderabad,Headphones,Electronics,5,21798,10,98091.00
3,1004,2025-01-04,Priya,Delhi,Headphones,Electronics,5,31999,5,151995.25
4,1005,2025-01-05,Priya,Delhi,Shirt,Clothing,10,33839,5,321470.50

In [3]:
#1. What is the total sales of the company?
df["Sales"].sum()

np.float64(7638209.75)

In [4]:
#2. What is the total quantity sold?
df["Quantity"].sum()

np.int64(295)

In [8]:
#3. What is the average sales amount?
df["Sales"].mean()

np.float64(152764.195)

In [7]:
df.loc[1,"City"]

'Mumbai'

In [9]:
#4. What is the maximum sales amount?
df["Sales"].max()

444096.0

In [10]:
#5. What is the minimum sales amount?
df["Sales"].min()

278.1

In [13]:
#1. Find total sales for each category using GroupBy.
df.groupby("Category")["Sales"].sum()

Category
Clothing       1991641.70
Electronics    2603308.95
Furniture      1766383.70
Grocery        1276875.40
Name: Sales, dtype: float64

In [14]:
#2. Find total sales for each city using GroupBy.
df.groupby("City")["Sales"].sum()

City
Bengaluru     913891.80
Delhi        2815590.70
Hyderabad    1237196.80
Mumbai       2029128.15
Pune          642402.30
Name: Sales, dtype: float64

In [16]:
#3. Find total quantity sold for each product using GroupBy.
df.groupby("Product")["Quantity"].sum()

Product
Bread         18
Chair         21
Headphones    40
Jeans         44
Laptop         9
Mobile        46
Rice          20
Shirt         50
Sofa          18
Table         29
Name: Quantity, dtype: int64

In [17]:
#4. Find average sales for each category using GroupBy.
df.groupby("Category")["Sales"].mean()

Category
Clothing       142260.121429
Electronics    162706.809375
Furniture      160580.336364
Grocery        141875.044444
Name: Sales, dtype: float64

In [18]:
#5. Find maximum sales for each city using GroupBy.
df.groupby("City")["Sales"].max()

City
Bengaluru    298389.0
Delhi        355276.8
Hyderabad    216666.0
Mumbai       444096.0
Pune         323971.2
Name: Sales, dtype: float64

In [19]:
#6. Find minimum sales for each category using GroupBy.
df.groupby("Category")["Sales"].min()

Category
Clothing       12060.0
Electronics      278.1
Furniture      12470.4
Grocery         9796.8
Name: Sales, dtype: float64

In [20]:
#7. Count the number of orders placed by each customer using GroupBy.
df.groupby("Customer_Name")["Order_ID"].count()

Customer_Name
Amit      1
Anjali    6
Arjun     9
Mohit     5
Neha      6
Pooja     9
Priya     5
Rahul     3
Simran    6
Name: Order_ID, dtype: int64

In [21]:
df.shape

(50, 10)

In [22]:
#8. Find total discount given for each product using GroupBy.
df.groupby("Product")["Discount"].sum()

Product
Bread         40
Chair         15
Headphones    60
Jeans         60
Laptop        40
Mobile        70
Rice          40
Shirt         75
Sofa          25
Table         75
Name: Discount, dtype: int64

In [23]:
#9. Find total sales generated by each customer using GroupBy.
df.groupby("Customer_Name")["Sales"].sum()

Customer_Name
Amit       165818.00
Anjali     438476.90
Arjun     1770334.45
Mohit      955419.70
Neha      1241539.85
Pooja      789498.05
Priya      639467.15
Rahul      271228.80
Simran    1366426.85
Name: Sales, dtype: float64

In [24]:
#10. Find average quantity sold for each category using GroupBy.
df.groupby("Category")["Quantity"].mean()

Category
Clothing       6.714286
Electronics    5.937500
Furniture      6.181818
Grocery        4.222222
Name: Quantity, dtype: float64

In [25]:
#11. Find total sales and total quantity for each category using GroupBy.
df.groupby("Category").agg({"Quantity":"sum","Sales":"sum"})

             Quantity       Sales
Category
Clothing           94  1991641.70
Electronics        95  2603308.95
Furniture          68  1766383.70
Grocery            38  1276875.40

In [38]:
#12. Find total sales and average sales for each city using GroupBy.
df.groupby("City")["Sales"].agg(["sum","mean"])

                  sum           mean
City
Bengaluru   913891.80  114236.475000
Delhi      2815590.70  175974.418750
Hyderabad  1237196.80  112472.436364
Mumbai     2029128.15  184466.195455
Pune        642402.30  160600.575000

In [36]:
#13. Find maximum and minimum sales for each product using GroupBy.
df.groupby("Product")["Sales"].agg(["max","min"])

                  max       min
Product
Bread       216666.00   38139.0
Chair       281540.00  107276.8
Headphones  338299.20     278.1
Jeans       308356.20   25120.0
Laptop      107816.80   78624.0
Mobile      444096.00   11080.8
Rice        323971.20    9796.8
Shirt       391000.00   12060.0
Sofa        278311.05   15610.0
Table       317452.05   12470.4

In [35]:
#14. Find top 5 customers based on total sales using GroupBy.
df.groupby("Customer_Name")["Sales"].sum().sort_values().head(5)

Customer_Name
Amit      165818.00
Rahul     271228.80
Anjali    438476.90
Priya     639467.15
Pooja     789498.05
Name: Sales, dtype: float64

In [39]:
#15. Find the category with the highest sales using GroupBy.
df.groupby("Category")["Sales"].max()

Category
Clothing       391000.00
Electronics    444096.00
Furniture      317452.05
Grocery        323971.20
Name: Sales, dtype: float64

In [40]:
#16. Find the city with the highest average sales using GroupBy.
df.groupby("City")["Sales"].mean().sort_values().head()

City
Hyderabad    112472.436364
Bengaluru    114236.475000
Pune         160600.575000
Delhi        175974.418750
Mumbai       184466.195455
Name: Sales, dtype: float64

In [41]:
#17. Find total sales for each Category and City combination using GroupBy.
df.groupby(["Category","City"])["Sales"].sum()

Category     City
Clothing     Bengaluru     131203.00
             Delhi         597253.70
             Hyderabad     419018.80
             Mumbai        535810.00
             Pune          308356.20
Electronics  Bengaluru     432245.80
             Delhi        1177939.90
             Hyderabad     154200.60
             Mumbai        838644.55
             Pune             278.10
Furniture    Bengaluru     119504.00
             Delhi        1040397.10
             Hyderabad      95359.00
             Mumbai        511123.60
Grocery      Bengaluru     230939.00
             Hyderabad     568618.40
             Mumbai        143550.00
             Pune          333768.00
Name: Sales, dtype: float64

In [42]:
#18. Find total quantity for each Category and Product combination using GroupBy.
df.groupby(["Category","Product"])["Quantity"].sum()

Category     Product
Clothing     Jeans         44
             Shirt         50
Electronics  Headphones    40
             Laptop         9
             Mobile        46
Furniture    Chair         21
             Sofa          18
             Table         29
Grocery      Bread         18
             Rice          20
Name: Quantity, dtype: int64

In [43]:
#19. Find average discount for each city using GroupBy.
df.groupby("City")["Discount"].sum()

City
Bengaluru     20
Delhi        175
Hyderabad    160
Mumbai        90
Pune          55
Name: Discount, dtype: int64

In [44]:
#20. Find total sales for each discount percentage using GroupBy.
df.groupby("Discount")["Sales"].sum()

Discount
0     1608251.00
5     1389213.50
10    1840736.70
15    1233801.35
20    1566207.20
Name: Sales, dtype: float64

In [47]:
#21. Find the number of orders in each category using GroupBy.
df.groupby("Category")["Order_ID"].count()

Category
Clothing       14
Electronics    16
Furniture      11
Grocery         9
Name: Order_ID, dtype: int64

In [48]:
#22. Find the number of orders in each city using GroupBy.
df.groupby("City")["Order_ID"].count()

City
Bengaluru     8
Delhi        16
Hyderabad    11
Mumbai       11
Pune          4
Name: Order_ID, dtype: int64

In [52]:
#23. Find total revenue generated by each product using GroupBy.
df["Revenue"]=df["Unit_Price"] * df["Quantity"]

df.groupby("Product")["Revenue"].sum()

Product
Bread          607747
Chair          527252
Headphones    1055432
Jeans          947822
Laptop         233051
Mobile        1591056
Rice           769946
Shirt         1332658
Sofa           490113
Table          970057
Name: Revenue, dtype: int64

In [58]:

df.head()

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Revenue
0,1001,2025-01-01,Simran,Delhi,Sofa,Furniture,9,32551,5,278311.05,292959
1,1002,2025-01-02,Mohit,Mumbai,Laptop,Electronics,2,49140,20,78624.00,98280
2,1003,2025-01-03,Arjun,Hyderabad,Headphones,Electronics,5,21798,10,98091.00,108990
3,1004,2025-01-04,Priya,Delhi,Headphones,Electronics,5,31999,5,151995.25,159995
4,1005,2025-01-05,Priya,Delhi,Shirt,Clothing,10,33839,5,321470.50,338390

In [59]:
#24. Find total sales for each customer in each city using GroupBy.
df.groupby(["City","Customer_Name"])["Sales"].sum()

City       Customer_Name
Bengaluru  Anjali           133856.80
           Arjun            192800.00
           Neha             113032.00
           Pooja             18171.00
           Priya             38139.00
           Rahul            119504.00
           Simran           298389.00
Delhi      Amit             165818.00
           Anjali            15610.00
           Arjun            829044.85
           Mohit            338299.20
           Neha             356574.00
           Pooja            358467.85
           Priya            473465.75
           Simran           278311.05
Hyderabad  Anjali           288732.00
           Arjun            158593.40
           Mohit             82888.60
           Pooja            403062.40
           Priya             12470.40
           Simran           291450.00
Mumbai     Arjun            281540.00
           Mohit            534231.90
           Neha             447962.65
           Priya            115392.00
           Rahul            151724.80
           Simran           498276.80
Pune       Anjali              278.10
           Arjun            308356.20
           Neha             323971.20
           Pooja              9796.80
Name: Sales, dtype: float64

In [60]:
#25. Find total sales, average sales, maximum sales, and minimum sales for each category using GroupBy.
df.groupby("Category")["Sales"].agg(["sum","mean","max","min"])

                    sum           mean        max      min
Category
Clothing     1991641.70  142260.121429  391000.00  12060.0
Electronics  2603308.95  162706.809375  444096.00    278.1
Furniture    1766383.70  160580.336364  317452.05  12470.4
Grocery      1276875.40  141875.044444  323971.20   9796.8

In [61]:
#26. Create a pivot table showing total sales by category.
pd.pivot_table(
    df,
    values="Sales",
    index="Category",
    aggfunc="sum"
)

                  Sales
Category
Clothing     1991641.70
Electronics  2603308.95
Furniture    1766383.70
Grocery      1276875.40

In [62]:
#27. Create a pivot table showing total sales by city.
pd.pivot_table(
    df,
    values="Sales",
    index="City",
    aggfunc="sum"
)

                Sales
City
Bengaluru   913891.80
Delhi      2815590.70
Hyderabad  1237196.80
Mumbai     2029128.15
Pune        642402.30

In [63]:
#28. Create a pivot table showing average sales by category.
pd.pivot_table(
    df,
    values="Sales",
    index="Category",
    aggfunc="mean"
)

                     Sales
Category
Clothing     142260.121429
Electronics  162706.809375
Furniture    160580.336364
Grocery      141875.044444

In [64]:
#29. Create a pivot table showing total quantity by product.
pd.pivot_table(
    df,
    values="Quantity",
    index="Product",
    aggfunc="sum"
)

            Quantity
Product
Bread             18
Chair             21
Headphones        40
Jeans             44
Laptop             9
Mobile            46
Rice              20
Shirt             50
Sofa              18
Table             29

In [66]:
#30. Create a pivot table with Category as rows and City as columns showing Sales.
pd.pivot_table(
    df,
    values="Sales",
    index="Category",
    columns="City",
    aggfunc="sum"
)

City         Bengaluru      Delhi  Hyderabad     Mumbai      Pune
Category
Clothing      131203.0   597253.7   419018.8  535810.00  308356.2
Electronics   432245.8  1177939.9   154200.6  838644.55     278.1
Furniture     119504.0  1040397.1    95359.0  511123.60       NaN
Grocery       230939.0        NaN   568618.4  143550.00  333768.0

In [67]:
#31. Create a pivot table with Product as rows and City as columns showing Sales.
pd.pivot_table(
    df,
    values="Sales",
    index="Product",
    columns="City",
    aggfunc="sum"
)

City        Bengaluru      Delhi  Hyderabad     Mumbai      Pune
Product
Bread         38139.0        NaN   384179.6  143550.00       NaN
Chair        119504.0        NaN        NaN  388816.80       NaN
Headphones   324429.0  563439.25    98091.0    3866.65     278.1
Jeans             NaN  263723.20   130286.8  144810.00  308356.2
Laptop       107816.8        NaN        NaN   78624.00       NaN
Mobile            NaN  614500.65    56109.6  756153.90       NaN
Rice         192800.0        NaN   184438.8        NaN  333768.0
Shirt        131203.0  333530.50   288732.0  391000.00       NaN
Sofa              NaN  439156.25        NaN        NaN       NaN
Table             NaN  601240.85    95359.0  122306.80       NaN

In [68]:
#32. Create a pivot table with Category as rows and City as columns showing Quantity.
pd.pivot_table(
    df,
    values="Quantity",
    index="Category",
    columns="City",
    aggfunc="sum"
)

City         Bengaluru  Delhi  Hyderabad  Mumbai  Pune
Category
Clothing          17.0   35.0       16.0    17.0   9.0
Electronics       19.0   41.0       14.0    20.0   1.0
Furniture          7.0   35.0        5.0    21.0   NaN
Grocery            5.0    NaN       21.0     3.0   9.0

In [69]:
#33. Create a pivot table showing average sales by city.
pd.pivot_table(
    df,
    values="Sales",
    index="City",
    aggfunc="mean"
)

                   Sales
City
Bengaluru  114236.475000
Delhi      175974.418750
Hyderabad  112472.436364
Mumbai     184466.195455
Pune       160600.575000

In [70]:
#34. Create a pivot table showing maximum sales by category.
pd.pivot_table(
    df,
    values="Sales",
    index="Category",
    aggfunc="max"
)

                 Sales
Category
Clothing     391000.00
Electronics  444096.00
Furniture    317452.05
Grocery      323971.20

In [71]:
#35. Create a pivot table showing minimum sales by category.
pd.pivot_table(
    df,
    values="Sales",
    index="Category",
    aggfunc="min"
)

               Sales
Category
Clothing     12060.0
Electronics    278.1
Furniture    12470.4
Grocery       9796.8

In [72]:
#36. Create a pivot table showing total discount by city.
pd.pivot_table(
    df,
    values="Discount",
    index="City",
    aggfunc="sum"
)

           Discount
City
Bengaluru        20
Delhi           175
Hyderabad       160
Mumbai           90
Pune             55

In [73]:
#37. Create a pivot table showing total sales by customer.
pd.pivot_table(
    df,
    values="Sales",
    index="Customer_Name",
    aggfunc="sum"
)

                    Sales
Customer_Name
Amit            165818.00
Anjali          438476.90
Arjun          1770334.45
Mohit           955419.70
Neha           1241539.85
Pooja           789498.05
Priya           639467.15
Rahul           271228.80
Simran         1366426.85

In [74]:
#38. Create a pivot table showing average discount by category.
pd.pivot_table(
    df,
    values="Discount",
    index="Category",
    aggfunc="mean"
)

              Discount
Category
Clothing      9.642857
Electronics  10.625000
Furniture    10.454545
Grocery       8.888889

In [76]:
#39. Create a pivot table showing total sales and quantity by category.
pd.pivot_table(
    df,
    values=["Sales","Quantity"],
    index="Category",

    aggfunc="sum"
)

             Quantity       Sales
Category
Clothing           94  1991641.70
Electronics        95  2603308.95
Furniture          68  1766383.70
Grocery            38  1276875.40

In [77]:
#40. Create a pivot table showing total sales and discount by city.
pd.pivot_table(
    df,
    values=["Sales","Discount"],
    index="City",

    aggfunc="sum"
)

           Discount       Sales
City
Bengaluru        20   913891.80
Delhi           175  2815590.70
Hyderabad       160  1237196.80
Mumbai           90  2029128.15
Pune             55   642402.30

In [78]:
#41. Create a pivot table with Product as rows and Category as columns showing Quantity.
pd.pivot_table(
    df,
    values="Quantity",
    index="Product",
    columns="Category",
    aggfunc="sum"
)

Category    Clothing  Electronics  Furniture  Grocery
Product
Bread            NaN          NaN        NaN     18.0
Chair            NaN          NaN       21.0      NaN
Headphones       NaN         40.0        NaN      NaN
Jeans           44.0          NaN        NaN      NaN
Laptop           NaN          9.0        NaN      NaN
Mobile           NaN         46.0        NaN      NaN
Rice             NaN          NaN        NaN     20.0
Shirt           50.0          NaN        NaN      NaN
Sofa             NaN          NaN       18.0      NaN
Table            NaN          NaN       29.0      NaN

In [84]:
#42. Create a pivot table with Customer as rows and City as columns showing Sales.
pd.pivot_table(
    df,
    values="Sales",
    index="Customer_Name",
    columns="City"

)

City           Bengaluru        Delhi      Hyderabad      Mumbai      Pune
Customer_Name
Amit                 NaN  165818.0000            NaN         NaN       NaN
Anjali           66928.4   15610.0000  144366.000000         NaN     278.1
Arjun           192800.0  207261.2125   79296.700000  281540.000  308356.2
Mohit                NaN  338299.2000   82888.600000  178077.300       NaN
Neha            113032.0  178287.0000            NaN  223981.325  323971.2
Pooja            18171.0   89616.9625  134354.133333         NaN    9796.8
Priya            38139.0  236732.8750   12470.400000  115392.000       NaN
Rahul           119504.0          NaN            NaN   75862.400       NaN
Simran          298389.0  278311.0500  145725.000000  249138.400       NaN

In [85]:
#43. Create a pivot table showing total sales for each Discount percentage.
pd.pivot_table(
    df,
    values="Sales",
    index="Discount",

    aggfunc="sum"
)

               Sales
Discount
0         1608251.00
5         1389213.50
10        1840736.70
15        1233801.35
20        1566207.20

In [86]:
#44. Create a pivot table showing average sales for each Discount percentage.
pd.pivot_table(
    df,
    values="Sales",
    index="Discount",

    aggfunc="mean"
)

                  Sales
Discount
0         123711.615385
5         198459.071429
10        184073.670000
15        176257.335714
20        120477.476923

In [89]:
#45. Create a pivot table with Category as rows and Product as columns showing Sales.
pd.pivot_table(
    df,
    values="Sales",
    columns="Product",
    index="Category"
)

Product,Bread,Chair,Headphones,Jeans,Laptop,Mobile,Rice,Shirt,Sofa,Table
Category,,,,,,,,,,
Clothing,NaN,NaN,NaN,121025.171429,NaN,NaN,NaN,163495.071429,NaN,NaN
Electronics,NaN,NaN,123763.0,NaN,93220.4,237794.025,NaN,NaN,NaN,NaN
Furniture,NaN,169440.266667,NaN,NaN,NaN,NaN,NaN,NaN,146385.416667,163781.33
Grocery,113173.72,NaN,NaN,NaN,NaN,NaN,177751.7,NaN,NaN,NaN

In [91]:
#46. Create a pivot table showing total quantity by City and Category.
pd.pivot_table(
    df,
    values=["Quantity"],
    index=["City","Category"],

    aggfunc="sum"
)

                       Quantity
City      Category
Bengaluru Clothing           17
          Electronics        19
          Furniture           7
          Grocery             5
Delhi     Clothing           35
          Electronics        41
          Furniture          35
Hyderabad Clothing           16
          Electronics        14
          Furniture           5
          Grocery            21
Mumbai    Clothing           17
          Electronics        20
          Furniture          21
          Grocery             3
Pune      Clothing            9
          Electronics         1
          Grocery             9

In [92]:
#47. Create a pivot table showing average quantity by Category.
pd.pivot_table(
    df,
    values="Quantity",
    index="Category",
    aggfunc="mean"
)

             Quantity
Category
Clothing     6.714286
Electronics  5.937500
Furniture    6.181818
Grocery      4.222222

In [96]:
#48. Create a pivot table showing total sales by Category with Grand Total.
pd.pivot_table(
    df,
    values="Sales",
    index="Category",

    aggfunc="sum",
    margins=True,        # this adds totals
    margins_name="Total", # name for the total row/col

)

                  Sales
Category
Clothing     1991641.70
Electronics  2603308.95
Furniture    1766383.70
Grocery      1276875.40
Total        7638209.75

In [95]:
#49. Create a pivot table showing total sales by City with Grand Total.
pd.pivot_table(
    df,
    values="Sales",
    index="City",

    aggfunc="sum",
    margins=True,        # this adds totals
    margins_name="Total", # name for the total row/col

)

                Sales
City
Bengaluru   913891.80
Delhi      2815590.70
Hyderabad  1237196.80
Mumbai     2029128.15
Pune        642402.30
Total      7638209.75

In [98]:
#50. Create a pivot table showing Sales and Quantity together with Category as rows and City as columns including Grand Totals.
pd.pivot_table(
    df,
    values=["Sales","Quantity"],
    index="Category",
    columns="City",
    aggfunc="sum",
    margins=True,        # this adds totals
    margins_name="Total",# name for the total row/col
)

             Quantity                                         Sales  \
City        Bengaluru  Delhi Hyderabad Mumbai  Pune Total Bengaluru
Category
Clothing         17.0   35.0      16.0   17.0   9.0    94  131203.0
Electronics      19.0   41.0      14.0   20.0   1.0    95  432245.8
Furniture         7.0   35.0       5.0   21.0   NaN    68  119504.0
Grocery           5.0    NaN      21.0    3.0   9.0    38  230939.0
Total            48.0  111.0      56.0   61.0  19.0   295  913891.8


City             Delhi  Hyderabad      Mumbai      Pune       Total
Category
Clothing      597253.7   419018.8   535810.00  308356.2  1991641.70
Electronics  1177939.9   154200.6   838644.55     278.1  2603308.95
Furniture    1040397.1    95359.0   511123.60       NaN  1766383.70
Grocery            NaN   568618.4   143550.00  333768.0  1276875.40
Total        2815590.7  1237196.8  2029128.15  642402.3  7638209.75